name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Frontend - Install dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Frontend - Build
      working-directory: ./frontend
      run: npm run build
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Backend - Install dependencies
      working-directory: ./backend
      run: pip install -r requirements.txt
        
    - name: Backend - Lint
      working-directory: ./backend
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
